apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: alarms
  name: alarms
spec:
  containers:
    - image: radial/busyboxplus:curl
      name: alarms
      resources: {}
      tty: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}