apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
  namespace: kube-public
spec:
  containers:
  - image: avwsolutions/falco-demo:1
    name: webserver
    ports:
    - containerPort: 3333
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}